type NonBinTypeA = {
  dataID: number
  ロゴ画像名: string
  決済事業者番号: string
  決済事業者名称: string
  キャッシュレスサービス名称: string
  キャッシュレスサービス区分: string
  キャッシュレスサービス区分その他: string
  ハウスカードの確認: boolean
  ブランドサービス: string
  特設WebURL: string
  検索サービス: string
  消費者向け問合せ窓口1名称: string
  消費者向け問合せ窓口1受付時間: string
  消費者向け問合せ窓口1電話番号: string
  消費者向け問合せ窓口1受付時間の補足等: string
  消費者向け問合せ窓口2名称: string
  消費者向け問合せ窓口2受付時間: string
  消費者向け問合せ窓口2電話番号: string
  消費者向け問合せ窓口2受付時間の補足等: string
  消費者向け問合せ窓口3名称: string
  消費者向け問合せ窓口3受付時間: string
  消費者向け問合せ窓口3電話番号: string
  消費者向け問合せ窓口3受付時間の補足等: string
  消費者向け問合せ窓口4名称: string
  消費者向け問合せ窓口4受付時間: string
  消費者向け問合せ窓口4電話番号: string
  消費者向け問合せ窓口4受付時間の補足等: string
  消費者向け問合せ窓口5名称: string
  消費者向け問合せ窓口5受付時間: string
  消費者向け問合せ窓口5電話番号: string
  消費者向け問合せ窓口5受付時間の補足等: string
}
